#!/usr/bin/env python3

import sys
import pyotp
import os
from qr_code_generator import generate_qr_code
from otp_generator import generate_otp

SECRET_FILE = "secret.txt"


def save_secret(secret):
    with open(SECRET_FILE, 'w') as f:
        f.write(secret)

def read_secret():
    if not os.path.exists(SECRET_FILE):
        print(f"Error: Secret file '{SECRET_FILE}' does not exist. Please generate a QR code first.\nOr, if you're super cool and you already have a secret, simply run:\n./submission --get-otp <secret>")
        sys.exit(1)
    with open(SECRET_FILE, 'r') as f:
        return f.read().strip()

def main():
    if len(sys.argv) < 2:
        print("Usage: ./submission --generate-qr | --get-otp")
        return
    
    command = sys.argv[1]

    if command == "--generate-qr":
        if len(sys.argv) == 3:
            user_id = sys.argv[2]
        else:
            user_id = "42"
        secret = pyotp.random_base32()
        generate_qr_code(user_id, secret)
        save_secret(secret)
        print(f"Secret: {secret}")
    elif command == "--get-otp":
        if len(sys.argv) == 3:
            secret = sys.argv[2]
        else:
            secret = read_secret()
        generate_otp(secret)
    else:
        print("Invalid command")


if __name__ == "__main__":
    main()
